server:
  port: 9998
spring:
  application:
    name: dubbo-spring-boot-starter
  dubbo:
    application:
      name: consumer
    registry:
      address: 111.231.99.77
      port: 2181
    protocol:
      name: dubbo
      prot: 20880

# 配置连接MySQL信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.99.77:3306/upload?characterEncoding=utf-8&useSSL=false
    username: aaryn
    password: superman713
    # 使用阿里的Druid配置数据库方便进行SQL监控
    druid:
    # 初始化大小、最小、最大连接数
      initial-size: 3
      min-idle: 3
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 监控后台账号和密码
      stat-view-servlet:
        login-password: admin
        login-username: admin
      # 配置 StatFilter
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
